### ISSUE TITLE
Busy wait loops keep JavaFixHistoryMiner from working

### ISSUE THREAD

**Issue by jlanawalt** [FXCMAPI/FXCM-API-Offerings#1]
Most of the time when I run the JavaFixHistoryMiner it never completes. It gets stuck in one of the while(!requestComplete) {} busy wait loops. Maybe this works fine on a single processor machine or something.

Some kind of thread synchronization should be used instead of busy wait, or at least make requestComplete volatile.

**Comment by FXCMAPI** [comment]
Hello Jacob

Thank you for your comments and contribution.
We will take a look and update you the progress.

Best regards
Lei

**Comment by FXCMAPI** [comment]
Hello Jacob,

Thank you for your message and interest in our project.
We were unable to cause the bug you have described as we do not have easy access to multi-processor machines and it worked fine on a single-CPU PC.
We will, however, graciously accept your patch proposal.
It looks like it works just as good on a normal PC and it looks like it would future-proof the program if someone wanted to make it multi-threaded.
Thank you.

Best Regards,
Pawel

**Comment by neoxu999** [comment]
The history data only returns me the first two time series. 
If I request another one, it will not return data. For example, I have AUD/USD H1, H4 and D1. I send history request interval 30s by each. H1 and H4 can get data. But D1 only return partial data.
