### ISSUE TITLE
Request to http://www.fxcorporate.com/Hosts.jsp returns empty content

### ISSUE THREAD

**Issue by duffar12** [FXCMAPI/FXCM-API-Offerings#3]
When I try to test the API by running the QATest tests I get an exception saying -
"Request to http://www.fxcorporate.com/Hosts.jsp returns empty content"
If URL is entered into a web browser, nothing is returned

**Comment by FXCMAPI** [comment]
Hi,

Try to download the latest Java Trading API from:
https://apiwiki.fxcorporate.com/api/java/trading_sdk.zip

also the terminal should ne “Demo” (its case sensitive)
server=”http://www.fxcorporate.com/Hosts.jsp”

Regards,
Daniel Halpert
